import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";

import { cn } from "@/lib/utils";
import Link from "next/link";
import { CircleUser, Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import Sidebar from "@/components/layout/side-bar/side-bar";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import Providers from "@/redux/Provider";
import { useTransition } from "react";
import { toast } from "@/components/ui/use-toast";
import { signOut } from "@/lib/actions/index";
import Topbar from "@/components/layout/top-bar/top-bar";
const montserrat = Montserrat({
  subsets: ["cyrillic"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const onSignOut = async () => {
    toast({
      description: "Logging out...",
    });
    await new Promise((resolve) => setTimeout(resolve, 2000));
    await signOut();
  };

  return (
    <html lang="en">
      <body className={cn("font-montserrat", montserrat.variable)}>
        <Providers>
          <div className="w-full min-h-screen hidden bg-red-400 max-lg:flex justify-center place-items-center">
            <h1 className="text-2xl text-white">Abrihi sa dakong screen goy</h1>
          </div>
          <div className="max-lg:hidden grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr] relative">
            <Sidebar />
            <div className="flex flex-col">
              <Topbar />
              {children}
            </div>
          </div>
          <Sonner />
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
