import React from "react";
import type { Metadata } from "next";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/app/components/ui/resizable";

export const metadata: Metadata = {
  title: "Stocks",
  description: "Generated by create next app",
};

export default function Stocks() {
  return (
    <ResizablePanelGroup
      direction="horizontal"
      className="h-full  w-full rounded-lg border"
    >
      <ResizableHandle withHandle />
      <ResizablePanel className="w-full"></ResizablePanel>
    </ResizablePanelGroup>
  );
}
